# Generated by Django 4.2.2 on 2023-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_artist_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='yt_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
